## Series

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4,7,-5,3], index=['a','b','c','d'])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [ ]:
obj2['a']

np.int64(4)

In [ ]:
obj2['c']

np.int64(-5)

In [ ]:
obj2[['c','a','d']]

c   -5
a    4
d    3
dtype: int64

In [ ]:
#obj2[0] #does't work

In [ ]:
obj2[obj2>2]

a    4
b    7
d    3
dtype: int64

In [ ]:
obj2 * 2

a     8
b    14
c   -10
d     6
dtype: int64

In [ ]:
np.exp(obj2)

a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64

In [ ]:
print('b' in obj2)

True

In [ ]:
'e' in obj2

False

In [ ]:
#Create a dictionary
sdata = {'Ohio': 35000, 'Texas': 54000, 'Oregan': 23780, 'Utah': 34568}

# Move it into a Pandas Series
obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     54000
Oregan    23780
Utah      34568
dtype: int64

In [ ]:
# Send back to a Dictionary
obj3.to_dict()

{'Ohio': 35000, 'Texas': 54000, 'Oregan': 23780, 'Utah': 34568}

In [ ]:
states = {'California', 'Ohio','Texas','Oregan'}

#This will override the order of the dictionary keys
obj4 = pd.Series(sdata,index=states)

In [ ]:
# Note Californa is NaN since there is no sdata for it. Utah is not included since there is no index for it.
print(obj4)

Texas         54000.0
Oregan        23780.0
Ohio          35000.0
California        NaN
dtype: float64

In [ ]:
pd.isna(obj4)

Texas         False
Oregan        False
Ohio          False
California     True
dtype: bool

In [ ]:
pd.notna(obj4)

Texas          True
Oregan         True
Ohio           True
California    False
dtype: bool

In [ ]:
obj4.isna()

Texas         False
Oregan        False
Ohio          False
California     True
dtype: bool

In [ ]:
obj4.notna()

Texas          True
Oregan         True
Ohio           True
California    False
dtype: bool

In [ ]:
obj3

Ohio      35000
Texas     54000
Oregan    23780
Utah      34568
dtype: int64

In [ ]:
obj4

Texas         54000.0
Oregan        23780.0
Ohio          35000.0
California        NaN
dtype: float64

In [ ]:
#Returns NaN where labels don't match (missing in either Series)
obj3 + obj4

California         NaN
Ohio           70000.0
Oregan         47560.0
Texas         108000.0
Utah               NaN
dtype: float64

In [ ]:
# California: 0 + NaN = NaN (still NaN)
# Ohio: 35000 + 35000 = 70000
# Utah: 34568 + 0 = 34568
obj3.add(obj4, fill_value=0)

California         NaN
Ohio           70000.0
Oregan         47560.0
Texas         108000.0
Utah           34568.0
dtype: float64

In [ ]:
# Align obj3 to obj4's index, filling missing with 0
obj3_aligned = obj3.reindex(obj4.index, fill_value=0)
obj3_aligned + obj4

Texas         108000.0
Oregan         47560.0
Ohio           70000.0
California         NaN
dtype: float64

In [ ]:
obj4

Texas         54000.0
Oregan        23780.0
Ohio          35000.0
California        NaN
dtype: float64

In [ ]:
obj4.index.name = 'state'
obj4.name = 'population'

obj4

state
Texas         54000.0
Oregan        23780.0
Ohio          35000.0
California        NaN
Name: population, dtype: float64

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.index = ['Tom','Dick','Harry','Sue']
obj

Tom      4
Dick     7
Harry   -5
Sue      3
dtype: int64

## Dataframes

In [33]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year' : [2000, 2001, 2002, 2001, 2002, 2003],
    'pop'  : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
              }
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [34]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [35]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
frame = pd.DataFrame(data, columns =['year', 'state', 'pop'])
frame

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [37]:
frame2 = pd.DataFrame(data, columns =['year', 'state', 'pop', 'debt'])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [39]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [40]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [41]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [42]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [43]:
frame2.debt

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
Name: debt, dtype: object

In [44]:
frame2['debt'] = 16.5

In [45]:
frame2.debt

0    16.5
1    16.5
2    16.5
3    16.5
4    16.5
5    16.5
Name: debt, dtype: float64

In [46]:
frame2['debt'] = np.arange(6)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5     0
1  2001    Ohio  1.7     1
2  2002    Ohio  3.6     2
3  2001  Nevada  2.4     3
4  2002  Nevada  2.9     4
5  2003  Nevada  3.2     5

In [47]:
val = pd.Series(
    [-1.2, -1.5, -1.2, -1.2], #, -1.2, -1.5, -1.2],
    #index=['two', 'four', 'five'] # mismatch
    index=[0, 2, 3, 5]
)
val

0   -1.2
2   -1.5
3   -1.2
5   -1.2
dtype: float64

In [48]:
frame2['debt'] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.5
3  2001  Nevada  2.4  -1.2
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2  -1.2

In [49]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  -1.2     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.5     True
3  2001  Nevada  2.4  -1.2    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2  -1.2    False

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='str')

In [51]:
del frame2['eastern']
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.5
3  2001  Nevada  2.4  -1.2
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2  -1.2

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [53]:
populations = {
    'Ohio' : {2000:1.5, 2001:1.7, 2002:3.6},
    'Nevada' : {2001:2.4, 2002:2.9}
}
type(populations)

dict

In [54]:
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [55]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [56]:
populations = {
    'Ohio' : {2000:1.5, 2001:1.7, 2002:3.6},
    'Nevada' : {2001:2.4, 2002:2.9}
}
pd.DataFrame(populations, index=[2001,2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [57]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [58]:
frame3['Ohio'][:-1]

2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [59]:
frame3['Nevada'][:2]

2000    NaN
2001    2.4
Name: Nevada, dtype: float64

In [68]:
pdata = {
    'Ohio':frame3['Ohio'][:-1],
    'Nevada': frame3['Nevada'][:3]
}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   NaN     2.9

In [70]:
frame3.index.name = 'year'
frame3.columns. name = 'state'
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [71]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [72]:
frame2 #different data types in structure so returns obj rather than array

   year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.5
3  2001  Nevada  2.4  -1.2
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2  -1.2

In [73]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.5],
       [2001, 'Nevada', 2.4, -1.2],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, -1.2]], dtype=object)

## Index Objects